### ISSUE TITLE
Follow up work for this to be released

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/support-hero-junior#1]
# V1 Release
Following up from this issue https://github.com/PostHog/posthog/issues/11209

First off - great work @MrKevinOConnell on getting this project started. I have some follow up that we should consider before releasing this:
1. We should for sure user PagerDuty as the source of truth for Support hero so that we just have a command like `/supporthero` which responds with info from PagerDuty and not allow this to be changed via slack
2. We need to reply to the thread, ephemerally and ensure it is not too often.

## Follow up ideas
1. Give the user some quick dropdown options to respond to for more context - "Are you on cloud or self-hosted?" for example.
2. Once given these answers we could even set some custom profile properties (maybe) so that we have the information for next time.

## TODO:
- [x] Fork to PostHog org - too much sensitive things to have this out of the org
- [x] Get up and running on flyio
- [ ] Automatic deploys to flyio
- [ ] Ensure posts are only sent every N minutes - this is tricky as we might need to store some state for the user in question
- [ ] Reply to a message in thread rather than directly

**Comment by kevoconnell** [comment]
Really excited to see how this develops @benjackwhite !
